### ISSUE TITLE
App crashes after update and doesn't open

### ISSUE THREAD

**Issue by demirdegerli** [yaxarat/lingvaandroid#52]
I upgraded to version 1.3.0 and the app crashes that app doesn't even open. When I downgrade to 1.2.6 it works as normal.

### Device Info
**Android version:** Android 11
**Phone model:** Redmi Note 8
**Firmware version:** MIUI 12.5.2

### Crash log
```
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{dev.atajan.lingva_android/dev.atajan.lingva_android.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3455)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3699)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8037)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
	at android.content.ContextWrapper.getResources(ContextWrapper.java:97)
	at android.view.ContextThemeWrapper.getResourcesInternal(ContextThemeWrapper.java:134)
	at android.view.ContextThemeWrapper.getResources(ContextThemeWrapper.java:128)
	at dev.atajan.lingva_android.common.ui.theme.ThemeKt.isSystemInNightMode(Theme.kt:6)
	at dev.atajan.lingva_android.MainActivity.<init>(MainActivity.kt:13)
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:1)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1254)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3443)
	... 11 more
```

**Comment by demirdegerli** [comment]
I think this is a duplicate of #48, closing the issue. Sorry.
